import Header from "@/componentes/Header/header";
import { Inter } from "next/font/google";
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css"
import Footer from "@/componentes/Footer/footer";
import Provider from "@/context/Provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TechStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </Provider>

  );
}
